# Makefile.deps created Mon Dec 13 20:20:20 PST 2010
commands.o: commands.cc commands.h inode.h trace.h util.h
inode.o: inode.cc trace.h inode.h util.h
trace.o: trace.cc trace.h
util.o: util.cc util.h trace.h
yshell.o: yshell.cc commands.h inode.h trace.h util.h
